app/Http/routes.php
<?php

Route::get('/', function() {
    return view('welcome');
});

Route::get('/home', function() {
    return view('welcome');
});

Route::group(['prefix'=>'admin/', 'middleware' => 'auth.checkrole:admin', 'as' => 'admin.'], function(){
    /* --------------------------------------------------------------------------------------------------------------
    /   MIDDLEWARE
    /  'middleware' => 'auth.checkrole' fica dentro do Kernel.php, onde todas as vezes que executar o admin
    /   vai para o middleware CheckRole onde será realizada as validações de autenticação
    /---------------------------------------------------------------------------------------------------------------*/

    // Categories
    Route::get('categories',['as'=>'categories.index', 'uses'=>'CategoriesController@index']);
    Route::get('categories/create', ['as' => 'categories.create', 'uses' => 'CategoriesController@create']);
    Route::get('categories/edit/{id}', ['as' => 'categories.edit', 'uses' => 'CategoriesController@edit']);
    Route::post('categories/update/{id}', ['as' => 'categories.update', 'uses' => 'CategoriesController@update']);
    Route::post('categories/store', ['as' => 'categories.store', 'uses' => 'CategoriesController@store']);
    // Fim Categories

    // Products
    Route::get('products',['as'=>'products.index', 'uses'=>'ProductsController@index']);
    Route::get('products/create', ['as' => 'products.create', 'uses' => 'ProductsController@create']);
    Route::get('products/edit/{id}', ['as' => 'products.edit', 'uses' => 'ProductsController@edit']);
    Route::get('products/destroy/{id}', ['as' => 'products.destroy', 'uses' => 'ProductsController@destroy']);
    Route::post('products/update/{id}', ['as' => 'products.update', 'uses' => 'ProductsController@update']);
    Route::post('products/store', ['as' => 'products.store', 'uses' => 'ProductsController@store']);
    // Fim Products

    // Clients
    Route::get('clients',['as'=>'clients.index', 'uses'=>'ClientsController@index']);
    Route::get('clients/create', ['as' => 'clients.create', 'uses' => 'ClientsController@create']);
    Route::get('clients/edit/{id}', ['as' => 'clients.edit', 'uses' => 'ClientsController@edit']);
    Route::post('clients/update/{id}', ['as' => 'clients.update', 'uses' => 'ClientsController@update']);
    Route::post('clients/store', ['as' => 'clients.store', 'uses' => 'ClientsController@store']);
    // Fim Clients

    // Orders
    Route::get('orders',['as'=>'orders.index', 'uses'=>'OrdersController@index']);
    Route::get('orders/edit/{id}',['as'=>'orders.edit', 'uses'=>'OrdersController@edit']);
    Route::post('orders/update/{id}',['as'=>'orders.update', 'uses'=>'OrdersController@update']);
    // Fim Orders

    // Cupoms
    Route::get('cupoms',['as'=>'cupoms.index', 'uses'=>'CupomsController@index']);
    Route::get('cupoms/create',['as'=>'cupoms.create', 'uses'=>'CupomsController@create']);
    Route::post('cupoms/store',['as'=>'cupoms.store', 'uses'=>'CupomsController@store']);
    // Fim Cupoms
});

// Pedidos
Route::group(['prefix'=>'customer', 'middleware' => 'auth.checkrole:client', 'as' => 'customer.'], function() {

    Route::get('order', ['as'=>'order.index', 'uses'=>'CheckoutController@index']);
    Route::get('order/create', ['as'=>'order.create', 'uses'=>'CheckoutController@create']);
    Route::post('order/store', ['as'=>'order.store', 'uses'=>'CheckoutController@store']);

});

Route::group(['middleware' => 'cors'], function() {
    // Rota que gera o token de acesso as apis
    Route::post('oauth/access_token', function() {
        // Esse cara chama o config -> oauth2.php e devolve o token em JSON
        return Response::json(Authorizer::issueAccessToken());
    });

    // Criando rotas de agrupamento das API'S
    Route::group(['prefix'=>'api', 'middleware' => 'oauth', 'as' => 'api.'], function() {

        // Rota de acesso a api de clientes
        Route::group(['prefix'=>'client', 'middleware'=>'oauth.checkrole:client',  'as' => 'client.'], function() {
            // Cria os método HTTP que a gente precisa baseado no nosso controller
            // https://laravel.com/docs/5.1/controllers#restful-supplementing-resource-controllers
            Route::resource('order','Api\Client\ClientCheckoutController',['except'=>['create','edit','destroy']]);
            // Listagem de produtos
            Route::get('products','Api\Client\ClientProductController@index');
        });

        // Rota de acesso a api de deliveryman
        Route::group(['prefix'=>'deliveryman', 'middleware'=>'oauth.checkrole:deliveryman', 'as' => 'deliveryman.'], function() {
            // Cria os método HTTP que a gente precisa baseado no nosso controller
            // https://laravel.com/docs/5.1/controllers#restful-supplementing-resource-controllers
            Route::resource('order', 'Api\Deliveryman\DeliverymanCheckoutController',['except'=>['create','edit','destroy','store']]);

            // Rota de atualização do status
            // Patch, atualização de alguns dados de uma parte de um recurso
            Route::patch('order/{id}/update-status', [
                'uses' => 'Api\Deliveryman\DeliverymanCheckoutController@updateStatus',
                'as' => 'orders.update_status']);
        });

        Route::get('authenticated', 'Api\UserController@authenticated');
        Route::get('cupom/{code}', 'Api\CupomController@show');

    });
});

app/Models/Order.php
<?php

namespace CodeDelivery\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Order extends Model implements Transformable
{
    use TransformableTrait;

    // Mass Assigment
    // Todas as vezes que criamos um registro, devemos exigir que passe esse campo no construtor
    protected $fillable = [
        'client_id',
        'user_deliveryman_id',
        'total',
        'status',
        'cupom_id'
    ];

    public function client()
    {
        return $this->belongsTo(Client::class);
    }

    public function cupom()
    {
        return $this->belongsTo(Cupom::class);
    }

    public function items()
    {
        // Um pedido pode ter vários itens
        return $this->hasMany(OrderItem::class);
    }

    public function deliveryman()
    {
        // Um pedido pode ter um entregador, um entregador é um usuário
        return $this->belongsTo(User::class, 'user_deliveryman_id', 'id');
    }

}

app/Http/Controllers/OrdersController.php
<?php
/**
 * Created by PhpStorm.
 * User: Elaine
 * Date: 25/04/2016
 * Time: 22:18
 */

namespace CodeDelivery\Http\Controllers;

use CodeDelivery\Repositories\OrderRepository;
use CodeDelivery\Repositories\UserRepositoryEloquent;
use Illuminate\Http\Request;

class OrdersController extends Controller
{
    /**
     * @var OrderRepository
     */
    private $orderRepository;

    public function __construct(OrderRepository $orderRepository)
    {
        $this->orderRepository = $orderRepository;
    }

    public function index()
    {
        $orders = $this->orderRepository->paginate();
        return view('admin.orders.index', compact('orders'));
    }

    public function edit($id, UserRepositoryEloquent $userRepository)
    {
        $list_status = [0 => 'Pendente', 1 => 'A caminho', 2 => 'Entregue', 3 => 'Cancelado'];
        $deliveryman = $userRepository->getDeliverymen();
        $order = $this->orderRepository->find($id);
        return view('admin.orders.edit', compact('order', 'list_status', 'deliveryman'));
    }

    public function update(Request $request, $id)
    {
        $all = $request->all();
        $this->orderRepository->update($all, $id);
        return redirect()->route('admin.orders.index');
    }
}

resources/views/customer/order/create.blade.php
<!-- Extende do template app.blade.php -->
@extends('app')
<!-- Dentro do yield('contend') incrementamos nosso conteúdo pelo section -->
@section('content')
    <div class="container">
        <h3>Novo Pedido</h3>
        @include('errors._check')
        <div class="container">
            {!! Form::open(['route'=>'customer.order.store', 'class'=>'form']) !!}
                <div class="form-group">
                    <label>Total:</label>
                    <p id="total"></p>
                    <a href="#" id="btnNewItem" class="btn btn-default">Novo Item</a>
                    <br/><br/>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Produto</th>
                                <th>Quantidade</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    <select class="form-control" name="items[0][product_id]">
                                        @foreach($products as $p)
                                            <option value="{{$p->id}}" data-price="{{$p->price}}">{{$p->name}} --- {{$p->price}}</option>
                                        @endforeach
                                    </select>
                                </td>
                                <td>
                                    {!! Form::text('items[0][qtd]', 1, ['class'=>'form-control']) !!}
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="form-group">
                    {!! Form::submit('Criar Pedido', ['class'=>'btn btn-primary']) !!}
                </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

<!-- O java script que ser escrito aqui será utilizado no final do template app.blade.php -->
@section('post-script')
    <script>
        $('#btnNewItem').click(function() {
            // Pega a última linha do tbody
            var row = $('table tbody > tr:last'),
                // Clona a nossa linha passada, ou seja copia
                newRow = row.clone(),
                // Busca a quantidade de linhas
                length = $("table tbody tr").length;

            // Percorre a linha clonada
            newRow.find('td').each(function() {
                var td = $(this),
                    // Pega o input e o select
                    input = td.find('input,select'),
                    // Pega o name
                    name = input.attr('name');

                input.attr('name', name.replace((length - 1) + "", length + ""));
            });
            // Pega os dados do input e insere uma nova linha
            newRow.find('input').val(1);
            newRow.insertAfter(row);
            calculateTotal();
        });

        // Recalcula preço ao selecionar produto
        $(document.body).on('click', 'select', function(){
            calculateTotal();
        });

        // Toda a vez que a quantidade for alterada, recalcula
        $(document.body).on('blur', 'input', function(){
            calculateTotal();
        });

        function calculateTotal() {
            var total = 0,
                // Pega o tamanho da tr
                trlen = $('table tbody tr').length,
                // Seta o valor da tr
                tr = null, price, qtd;

            // Percorre as trs
            for (var i=0; i<trlen; i++) {
                tr = $('table tbody tr').eq(i);
                price = tr.find(':selected').data('price');
                qtd = tr.find('input').val();
                total += price * qtd;
            }
            $("#total").html(total);
        }

    </script>
@endsection

resources/views/customer/order/index.blade.php
<!-- Extende do template app.blade.php -->
@extends('app')
<!-- Dentro do yield('contend') incrementamos nosso conteúdo pelo section -->
@section('content')
    <div class="container">
        <h3>Meus Pedidos</h3>
        <a href="{{route('customer.order.create')}}" class="btn btn-primary">Novo Pedido</a>
        <br/><br/>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Total</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
            @foreach($orders as $order)
                <tr>
                    <td>{{$order->id}}</td>
                    <td>{{$order->total}}</td>
                    <td>{{$order->status}}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {!! $orders->render() !!}
    </div>
@endsection